package util;

public interface View {
	int HOME = 1;
	int MAIN = 11;
	int CASH_RESET = 12;

	int MEMBER = 2;
	int MEMBER_SIGNUP = 21;
	int MEMBER_LOGIN = 22;
	int MEMBER_RESIGN = 23;
	
	int TICKET = 3;
	int TICKET_SEARCHING = 31;
	int TICKET_SEARCHING_STATION = 32;
	int TICKET_SEARCHING_ROUTE = 33;
	int TICKET_SEARCHING_BUS_SEAT = 34;
	int TICKET_BUY = 35;
	
	int REFUND = 4;
	int REFUND_SEARCHING_TICKET = 41;
	int REFUND_TICKET = 42;

	int MANAGE_LOGIN = 5;
	int MANAGE_MENU = 51;
	int MANAGE_BUS = 511;
	int MANAGE_SERVICE = 512;
	int MANAGE_SERVICE_INSERT = 5121;
	int MANAGE_SERVICE_DELETE = 5122;
	int MANAGE_STATION = 513;
	int MANAGE_STATION_INSERT = 5131;
	int MANAGE_STATION_DELETE = 5132;
	int MANAGE_SALES = 514;
	
	int TEST_PAGE = 999;
	
}
